### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by Amsalegebrehana** [Ashosy/DelaloProject#23]
Users model UI

**Comment by Amsalegebrehana** [comment]
Every one check the updates made and go through the tasks

**Comment by Amsalegebrehana** [comment]
Today was productive, we made some progress.
Don't forget tomorrows  meeting at 8:00 am(2:00)!!

**Comment by Selamawit926** [comment]
Drawer nav screen is almost done. And also when we push our branches let's make sure the master branch is upto date, the conflicts won't be easy to solve if we don't update it
