### ISSUE TITLE
Basic API 

### ISSUE THREAD

**Issue by Amsalegebrehana** [Ashosy/DelaloProject#9]
API setup and local database
- [x] Node js
- [x] express 
- [x] MongoDB

**Comment by BiniyamAb** [comment]
Guys, let's just continue our task management here right?

**Comment by BiniyamAb** [comment]
I don't think we did the relation ships between the our database models. should we do it on Friday?

**Comment by Amsalegebrehana** [comment]
> I don't think we did the relation ships between the our database models. should we do it on Friday?



> Guys, let's just continue our task management here right?

yes, you are right

**Comment by Amsalegebrehana** [comment]
> I don't think we did the relation ships between the our database models. should we do it on Friday?

Friday sounds good to me, What time is everyone available ?
